version: '2.4'
services:
  gps_logger:
    image: 'yourregistry/ncos_gps_logger:latest'
    container_name: gps_logger
    network_mode: bridge
    volumes:
      - $CONFIG_STORE
    mem_limit: 32M
    restart: unless-stopped
    logging:
      driver: json-file
